- src/components/ui/salesman/contractAndInvoices/PaymentButtonBar/PaymentButtonBar.jsx
- src/components/ui/salesman/contractEdit/ContractEditForm/ContractEditForm.jsx
- src/components/ui/salesman/contractViews/Contract/Contract.jsx
- src/components/ui/salesman/membersDetails/CategoriesModal/CategoriesModal.jsx
- src/components/ui/salesman/newCompanySteps/MembersStep/MembersStep.jsx
- src/components/ui/salesman/newCompanySteps/NewMembersTable/NewMembersTable.jsx
- src/components/ui/salesman/newCompanySteps/StepperIcons/StepperIcons.jsx
-   [x] Bugfix
Fixing eslint errors
-   [ ] Yes
-   [x] No
> perf: ⚡️ eslint fixing

- src/components/layout/topbarParts/BellNotifications/BellNotifications.view.jsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> style: 🎨 Change notifiction bell

- src/components/layout/topbarParts/MemberTopbar/MemberTopbar.view.jsx
-   [ ] Bugfix
-   [x] Code style update (formatting, local variables)
Home page search icon had #fff stroke
Disabled stroke
-   [ ] Yes
-   [x] No
> style: 🎨 Fixed search input icon

- src/App.jsx
- src/components/layout/PrivateRoute/PrivateRoute.view.jsx
- src/components/layout/TradingHours/TradingHours.view.jsx
- src/components/layout/topbarParts/BellNotifications/BellNotifications.jsx
- src/components/layout/topbarParts/BellNotifications/BellNotifications.view.jsx
- src/components/layout/topbarParts/TradingHourUnit/TradingHourUnit.view.jsx
- src/styles/MainStyles.js
-   [x] Bugfix
Home page top bar was not responsive
The top bar is now responsive
-   [ ] Yes
-   [x] No
> 8 home page top bar

- src/components/layout/TradingHours/TradingHours.view.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.view.jsx
- src/styles/MainStyles.js
-   [x] Bugfix
Home page top bar was not responding well to height changes
Now the top bar is responding as it should
-   [ ] Yes
-   [x] No
> fix: 🐞 home page top bar

- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/pages/GeneralHome/GeneralHome.style.js
- src/components/pages/GeneralHome/GeneralHome.view.jsx
-   [x] Bugfix
Home page calender is now responsive
-   [ ] Yes
-   [x] No
> style: 🎨 home page calendar is now responsive

- src/components/ui/members/ShowPublication/Content/Content.view.jsx
getting the value from props fix it probably this err occurred when
destructuring components
-   [X ] Bugfix
-   [ ] Yes
-   [X ] No
> fix: 🐞 preview crashed since there conentBlocks was undefined

- src/components/layout/NumberFormatCustom/NumberFormatCustom.jsx
- src/components/layout/NumberFormatCustom/NumberFormatCustom.style.js
- src/components/layout/NumberFormatCustom/NumberFormatCustom.view.jsx
- src/components/ui/reusables/NumberInputUnit/NumberInputUnit.jsx
- src/components/ui/reusables/NumberInputUnit/NumberInputUnit.style.js
- src/components/ui/reusables/NumberInputUnit/NumberInputUnit.view.jsx
- src/components/ui/salesman/contractViews/GeneralContractView/GeneralContractView.view.jsx
-   [X ] Bugfix
-   [ ] Yes
-   [ X] No
> fix: 🐞 fixing the NumberInputUnit component

- src/components/pages/LoginPage/LoginPage.style.js
- src/components/pages/LoginPage/LoginPage.view.jsx
-   [ ] Bugfix
-   [X] Other... Please describe: responsivity and style
-   [ ] Yes
-   [X] No
> style: 🎨 login form responsivity and styling

- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/pages/GeneralHome/GeneralHome.view.jsx
-   [ ] Bugfix
Fixed the calendar at home apge
-   [ ] Yes
-   [x] No
> refactor: 💡 home page calendar styles

- src/components/layout/TopBar/TopBar.jsx
- src/components/layout/TopBar/TopBar.style.js
- src/components/layout/TopBar/TopBar.view.jsx
- src/components/layout/topbarParts/AdminTopbar/AdminTopbar.view.jsx
- src/components/layout/topbarParts/MemberTopbar/MemberTopbar.jsx
- src/components/layout/topbarParts/MemberTopbar/MemberTopbar.view.jsx
- src/components/pages/LoginPage/LoginPage.view.jsx
- src/components/ui/reusables/CustomPopper/CustomPopper.jsx
- src/components/ui/reusables/CustomPopper/CustomPopper.style.js
- src/components/ui/reusables/CustomPopper/CustomPopper.view.jsx
- src/components/ui/reusables/SelectFormControl/SelectFormControl.jsx
- src/components/ui/reusables/SelectFormControl/SelectFormControl.style.js
- src/components/ui/reusables/SelectFormControl/SelectFormControl.view.jsx
- src/components/ui/reusables/SelectInputUnit/SelectInputUnit.jsx
- src/components/ui/reusables/SelectInputUnit/SelectInputUnit.style.js
- src/components/ui/reusables/SelectInputUnit/SelectInputUnit.view.jsx
- src/redux/auth/action.js
-   [ ] Bugfix
-   [X ] Refactoring (no functional changes, no api changes)
-   [ ] Yes
-   [X] No
> Topbar select

- src/components/pages/GeneralHome/GeneralHome.view.jsx
-   [ ] Bugfix
Styling at home page calendar
Changed the arrows for month switching and made the dates padding smaller
-   [ ] Yes
-   [x] No
> refactor: 💡 home page calendar arrows & padding

- src/components/pages/GeneralHome/GeneralHome.view.jsx
-   [ ] Bugfix
Home page calendar month color is black
Changed the Home page calendar month color to - #1C67FF
-   [ ] Yes
-   [x] No
> style: 🎨 home page calendar month color

- src/components/pages/GeneralHome/GeneralHome.style.js
- src/components/pages/GeneralHome/GeneralHome.view.jsx
- src/index.css
-   [ ] Bugfix
Changed the home page tabs hover color & font
-   [ ] Yes
-   [x] No
> refactor: 💡 home page tabs hover color & font

- .env.development
- src/components/AccountSettings/AccountSettings.js
- src/components/AccountSettings/Settings.js
- src/components/ui/admin/UserInfo/UserInfo.view.jsx
- src/components/ui/reusables/Settings/Settings.view.jsx
- src/components/ui/reusables/SettingsSection/SettingsSection.view.jsx
- src/redux/auth/action.js
-   [ ] Bugfix
No space in comments_replies as settings page
-   [ ] Yes
-   [x] No
> refactor: 💡 settings page comments_replies

- src/components/ui/author/allPublications/AllPublications/AllPublications.style.js
-   [ ] Bugfix
researches page total statistics was not responsive
researches page total statistics is now responsive
-   [ ] Yes
-   [x] No
> refactor: 💡 researches page total statistics is now responsive

- renovate.json
-   [ ] Bugfix
There is no bot for updating packages automatically
Added renovatebot - 
https://github.com/apps/renovate
https://docs.renovatebot.com/
-   [ ] Yes
-   [x] No
> feat: 🔥 Added renovatebot

- src/components/ui/author/DeadArticle/DeadArticle.jsx
- src/components/ui/members/ShowPublication/Events/Events.view.jsx
> fix: 🐞 publish disabled fixed for dead article and preview works

- src/components/layout/topbarParts/AdminTopbar/AdminTopbar.style.js
- src/components/layout/topbarParts/AdminTopbar/AdminTopbar.view.jsx
-   [ ] Bugfix
-   [X ] Code style update (formatting, local variables)
-   [ ] Yes
-   [X ] No
> style: 🎨 make admin top bar responsive

- package.json
-   [ ] Bugfix
You can use every package manager.
Added - https://www.npmjs.com/package/only-allow
That's explain it -
And that's what I added inside package.json - 
-   [ ] Yes
-   [x] No
> feat: 🔥 Added only-allow package

- src/components/ui/admin/UserInfo/UserInfo.view.jsx
> style: 🎨 fixing part of the styling

- .prettierignore
- package.json
-   [ ] Bugfix
Edited `package.json` file with new scripts, if you want to understand what I added, check the `peckage.json` file and see what you don't understand and you can read about each script with google.
-   [ ] Yes
-   [x] No
> refactor: 💡 package.json update

- src/styles/MainStyles.js
-   [X ] Bugfix
-   [ ] Yes
-   [ X] No
> style: 🎨 fixing the little blue stroke

- .eslintrc.js
-   [ ] Bugfix
Deleted - 'import/no-nodejs-modules': ['error'] from the rules because it's not needed and was added by mistake
-   [ ] Yes
-   [x] No
> refactor: 💡 edited eslint

- .eslintrc.js
-   [ ] Bugfix
Added `prettier` to `.eslintrc.js` extends
-   [ ] Yes
-   [x] No
> refactor: 💡 Updated eslint

- .github/workflows/commitlint.yml
-   [ ] Bugfix
Added commitlint.yml inside .github/workflows - https://github.com/conventional-changelog/commitlint
The `commitlint.yml` is checking the git commit msg
-   [ ] Yes
-   [x] No
> feat: 🔥 added commitlint.yml inside .github/workflows

- src/App.jsx
✅ Closes: yes
-   [ ] Bugfix
adding a router for each user that show his notification
-   [ ] Yes
-   [X] No
> refactor: 💡 adding to all users types notifications router

- .github/workflows/guardian.yml
-   [ ] Bugfix
Added - https://www.gitguardian.com/
The config file is - guardian.yml
-   [ ] Yes
-   [x] No
> feat: 🔥 Added gitguardian

- .eslintignore
- .eslintrc.js
- .github/workflows/integrate.yml
- .husky/pre-commit
- package.json
- src/components/AccountSettings/ContractsAndTrails.js
- src/components/Members/PublicationsGrid.js
- src/components/Members/WorldMap.js
- src/components/Notifications/AlertNotification.js
- src/components/layout/topbarParts/AdminTopbar/AdminTopbar.view.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/reusables/SettingsSection/SettingsSection.view.jsx
- src/components/ui/salesman/contractAndInvoices/ContractAndInvoicesContent/ContractAndInvoicesContent.view.jsx
- src/components/ui/salesman/contractAndInvoices/ContractRow/ContractRow.view.jsx
- src/components/ui/salesman/contractAndInvoices/PaymentButtonBar/PaymentButtonBar.view.jsx
- src/components/ui/salesman/contractViews/allContracts/ContractRow/ContractRow.view.jsx
- src/redux/SnackBar/reducer.js
- src/redux/auth/reducer.js
- src/services/websocket.js
- yarn.lock
-   [ ] Bugfix
Changed husky pre-commit from npx lint-staged to lint-staged
-   [ ] Yes
-   [x] No
> Husky update

- .github/workflows/integrate.yml
-   [ ] Bugfix
-   [x] CI related changes
Added integrate.yml file
-   [ ] Yes
-   [x] No
> ci: 🚀 Added integrate.yml

- .vscode/extensions.json
-   [ ] Bugfix
Added eslint to the extension.json file
-   [ ] Yes
-   [x] No
> refactor: 💡 Added eslint to .vscode/extensions.json

- .env.development
- lint-staged.config.js
- src/components/ui/salesman/companyDetails/CompanyInfo/CompanyInfo.view.jsx
- src/components/ui/salesman/companyDetails/ContractBlock/ContractBlock.view.jsx
- src/components/ui/salesman/companyDetails/InitialCompanyStateBlock/InitialCompanyStateBlock.view.jsx
- src/components/ui/salesman/membersDetails/MembersHeader/MembersHeader.view.jsx
- src/styles/InfoStyles.js
- src/styles/MainStyles.js
-   [ ] Bugfix
Companies page isn't responsive
Now the companies page is responsive
-   [ ] Yes
-   [x] No
> refactor: 💡 Fixed companies page responsiveness

- src/components/ui/reusables/Settings/Settings.view.jsx
-   [ ] Bugfix
Settings in settings page wasn't responsive
Settings are responsive
-   [ ] Yes
-   [x] No
> refactor: 💡 Fixed responsiveness in settings page

- src/components/layout/NumberFormatCustom/NumberFormatCustom.jsx
- src/components/layout/NumberFormatCustom/NumberFormatCustom.view.jsx
- src/components/ui/salesman/contractEdit/SideForm/SideForm.jsx
- src/components/ui/salesman/contractEdit/SideForm/SideForm.view.jsx
- src/components/ui/salesman/contractViews/Contract/Contract.jsx
- src/components/ui/salesman/contractViews/Contract/Contract.view.jsx
-   [X] Bugfix
-   [ ] Yes
-   [X] No
> fix: 🐞 fixing various bugs related to new contract and edited contract

- src/components/ui/reusables/DateInputUnit/DateInputUnit.style.js
- src/components/ui/reusables/DateInputUnit/DateInputUnit.view.jsx
- src/components/ui/reusables/NumberInputUnit/NumberInputUnit.view.jsx
- src/components/ui/salesman/contractViews/Contract/Contract.jsx
- src/components/ui/salesman/contractViews/GeneralContractView/GeneralContractView.jsx
- src/components/ui/salesman/contractViews/GeneralContractView/GeneralContractView.view.jsx
- src/components/ui/salesman/contractViews/SendContractView/SendContractView.style.js
- src/components/ui/salesman/contractViews/SendContractView/SendContractView.view.jsx
- src/customHooks/useSessionStorageRedux.js
- src/customHooks/useSessionStorageState.js
-   [X] Bugfix
-   [ ] Yes
-   [ X] No
> Contract page bugs

- src/components/ui/salesman/contractViews/allContracts/AllContract/AllContract.view.jsx
- src/components/ui/salesman/contractViews/allContracts/ContractRow/ContractRow.view.jsx
✅ Closes: no
-   [ ] Bugfix
the table is responsive and the blue thing is shown up
-   [ ] Yes
-   [X] No
> style: 🎨 styling the table and the blue thing in contracts

- src/components/AccountSettings/AccountSettings.jsx
- src/components/ui/reusables/EditProfile/EditProfile.style.js
- src/components/ui/reusables/EditProfile/EditProfile.view.jsx
- src/components/ui/reusables/NumberInputUnit/NumberInputUnit.view.jsx
- src/components/ui/reusables/PhoneInput/PhoneInput.style.js
- src/components/ui/reusables/PhoneInput/PhoneInput.view.jsx
- src/styles/AccountSettingsStyles.js
-   [ ] Bugfix
-   [X] Code style update (formatting, local variables)
-   [ ] Yes
-   [X] No
> style: 🎨 display element of edit profile

- src/components/ui/author/allPublications/AllPublications/AllPublications.style.js
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.jsx
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.style.js
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.view.jsx
-   [ ] Bugfix
Researches page publication descriptions isn't responsive
The page publication descriptions is now responsive
-   [ ] Yes
-   [x] No
> refactor: 💡 fixed researches page

- src/components/layout/topbarParts/AdminTopbar/AdminTopbar.style.js
- src/components/ui/admin/UserInfo/UserInfo.style.js
- src/components/ui/admin/UserInfo/UserInfo.view.jsx
-   [ ] Bugfix
In sales page for admin users in user info there is no profile picture. There are some responsive problems.
Added a profile picture & fixed responsive problems.
-   [ ] Yes
-   [x] No
> refactor: 💡 Added profile icon to sales page in admin & fixed topbar

- src/assets/icons/DefaultProfilePic.svg
- src/components/layout/TopBar/TopBar.jsx
- src/components/layout/topbarParts/UserIcon/UserIcon.view.jsx
- src/components/ui/admin/UserInfo/UserInfo.view.jsx
- src/js.js
-   [ ] Bugfix
When pressing on - 
There is an error - 
https://user-images.githubusercontent.com/94856098/161543567-6d1733d2-6fb5-46e5-a82b-a2a1b9072337.png
Fixed the error
-   [ ] Yes
-   [x] No
> refactor: 💡 Fixed salesman topbar profile select

- src/components/ui/reusables/DropZone/DropZone.view.jsx
-   [ ] Bugfix
There was no space in new company form
Added space to new company form
-   [ ] Yes
-   [x] No
> refactor: 💡 Added space to new company form

- src/components/ui/salesman/contractViews/Contract/Contract.view.jsx
- src/components/ui/salesman/newCompanySteps/MembersStep/MembersStep.style.js
- src/components/ui/salesman/newCompanySteps/MembersStep/MembersStep.view.jsx
- src/components/ui/salesman/newCompanySteps/NewCompanyStepper/NewCompanyStepper.style.js
- src/components/ui/salesman/newCompanySteps/NewCompanyStepper/NewCompanyStepper.view.jsx
- src/components/ui/salesman/newCompanySteps/NewMembersTable/NewMembersTable.style.js
-   [ ] Bugfix
The new company form isn't responsive & style isn't align
Fixed responsiveness & styling
-   [ ] Yes
-   [x] No
> refactor: 💡 fixed new company form

- src/components/layout/TradingHours/TradingHours.jsx
- src/components/layout/TradingHours/TradingHours.view.jsx
- src/components/layout/topbarParts/UserIcon/UserIcon.jsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> refactor: 💡 logout goes to the home page

- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/reusables/AutoCompleteUnit/AutoCompleteUnit.view.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.view.jsx
- src/components/ui/reusables/ChangePassword/ChangePassword.view.jsx
- src/components/ui/reusables/DateInputUnit/DateInputUnit.view.jsx
- src/components/ui/reusables/NumberInputUnit/NumberInputUnit.view.jsx
- src/components/ui/reusables/TextInputUnit/TextInputUnit.view.jsx
- src/components/ui/salesman/newCompanySteps/InfoStep/InfoStep.view.jsx
-   [X] Bugfix
-   [ ] Yes
-   [X] No
> fix: 🐞 typo in helperText

- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/redux/utils/utilsSlice.js
-   [x] Bugfix
-   [ ] Yes
-   [x] No
> fix: 🐞 fix the bug in the query of update attachments

- src/components/ui/admin/UserInfo/UserInfo.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/reusables/EditProfile/EditProfile.jsx
- src/components/ui/reusables/ExitPublicationAlert/ExitPublicationAlert.jsx
- src/components/ui/reusables/ExitPublicationAlert/ExitPublicationAlert.view.jsx
-   [X] Bugfix
-   [ ] Yes
-   [x] No
> refactor: 💡 fixing bugs in akert modal for unsaved changes

- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/members/ShowPublication/FullPublication/FullPublication.jsx
- src/components/ui/members/ShowPublication/FullPublication/FullPublication.view.jsx
-   [X] Bugfix
-   [ ] Yes
-   [ X] No
> refactor: 💡 adapting publication preview to changes

- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.jsx
> Auto save2

- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/reusables/SubHeader/SubHeader.view.jsx
- src/styles/AuthorsStyles.js
-   [ ] Bugfix
-   [X ] Other... Please describe: UI styling
-   [ ] Yes
-   [ X] No
> New pub UI

- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/DeadArticle/DeadArticle.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
-   [X ] Bugfix
-   [ ] Yes
-   [X ] No
> refactor: 💡 validation fixes for dead article

- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/members/ShowPublication/FullPublication/FullPublication.view.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.view.jsx
- src/components/ui/reusables/DropZone/DropZone.view.jsx
- src/components/ui/reusables/ExitPublicationAlert/ExitPublicationAlert.view.jsx
- src/components/ui/reusables/SubHeader/SubHeader.jsx
- src/components/ui/reusables/SubHeader/SubHeader.view.jsx
- src/styles/AuthorsStyles.js
- src/styles/InfoStyles.js
> fix: 🐞 ui corrections for author screens

- src/components/layout/TopBar/TopBar.jsx
- src/components/layout/TradingHours/TradingHours.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.jsx
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.view.jsx
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.style.js
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.view.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.view.jsx
- src/redux/reducers.js
- src/redux/search/searchSlice.js
-   [X] Bugfix
-   [ ] Yes
-   [X] No
> feat: 🔥 login button is visible

- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.style.js
> style: 🎨 some changes to publication card

- src/components/layout/TopBar/TopBar.style.js
- src/components/layout/TopBar/TopBar.view.jsx
- src/components/ui/author/allPublications/AllPublications/AllPublications.style.js
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.style.js
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.view.jsx
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.style.js
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.view.jsx
- src/components/ui/author/allPublications/TabPanel/TabPanel.style.js
-   [ ] Bugfix
-   [] Yes
-   [X] No
> style: 🎨 styling all publicationTabs

- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.style.js
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.view.jsx
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.style.js
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.view.jsx
- src/components/ui/author/allPublications/TabPanel/TabPanel.style.js
- src/components/ui/members/ShowPublication/Content/Content.view.jsx
- src/components/ui/members/ShowPublication/FullPublication/FullPublication.jsx
- src/components/ui/reusables/DropZone/DropZone.view.jsx
- src/components/ui/reusables/DropZoneMulti/DropZoneMulti.view.jsx
- src/components/ui/reusables/ExitPublicationAlert/ExitPublicationAlert.view.jsx
- src/styles/AuthorsStyles.js
- src/styles/InfoStyles.js
-   [ ] Bugfix
-   [X] Other... Please describe: styling 
-   [ ] Yes
-   [ X] No
> All pubs fixes

- src/components/layout/PrivateRoute/PrivateRoute.view.jsx
- src/components/layout/TradingHours/TradingHours.jsx
- src/components/layout/TradingHours/TradingHours.view.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.style.js
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.view.jsx
-   [ ] Bugfix
-   [ ] Yes
-   [X] No
> refactor: 💡 refactoring the is_publishable functionality

- src/components/layout/PrivateRoute/PrivateRoute.view.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat: 🔥 handle err

- src/components/layout/PrivateRoute/PrivateRoute.view.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.view.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.view.jsx
- src/components/ui/reusables/EditProfile/EditProfile.view.jsx
- src/components/ui/salesman/AddMemberModal/AddMemberModal.view.jsx
- src/components/ui/salesman/newCompanySteps/MembersStep/MembersStep.jsx
- src/components/ui/salesman/newCompanySteps/MembersStep/MembersStep.view.jsx
- src/styles/AuthorsStyles.js
- src/utils/helpers/validationFunctions.js
> fix: 🐞 validation bugs - dead article

- src/components/ui/author/allPublications/AllPublications/AllPublications.view.jsx
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.jsx
- src/components/ui/reusables/Pagination/Pagination.jsx
- src/components/ui/reusables/Pagination/Pagination.style.js
- src/components/ui/reusables/Pagination/Pagination.view.jsx
- src/redux/categories/categoriesSlice.js
- src/redux/reducers.js
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> Categories

- src/components/ui/author/allPublications/AllPublications/AllPublications.view.jsx
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.jsx
- src/components/ui/reusables/Pagination/Pagination.jsx
- src/components/ui/reusables/Pagination/Pagination.style.js
- src/components/ui/reusables/Pagination/Pagination.view.jsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
> fix: 🐞 deleting publication slice

- src/App.jsx
- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/reusables/SelectFormControl/SelectFormControl.jsx
- src/redux/categories/categoriesSlice.js
- src/redux/reducers.js
- src/utils/helpers/helperFunctions.js
-   [ ] Bugfix
-   [ X] Feature
-   [ ] Yes
-   [X ] No
> feat: 🔥 home page calls continue

- src/assets/icons/PolygonDown.svg
- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/pages/GeneralHome/GeneralHome.style.js
- src/components/pages/GeneralHome/GeneralHome.view.jsx
- src/components/ui/author/AuthorsNewArticleModal/AuthorsNewArticleModal.style.js
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.jsx
- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.view.jsx
- src/components/ui/reusables/SelectFormControl/SelectFormControl.jsx
- src/components/ui/reusables/SelectFormControl/SelectFormControl.style.js
- src/components/ui/reusables/SelectFormControl/SelectFormControl.view.jsx
- src/redux/categories/categoriesSlice.js
-   [ ] Bugfix
-   [X ] Feature
-   [ ] Yes
-   [X ] No
> feat: 🔥 homepage calls almost done

- src/components/pages/LoginPage/LoginPage.jsx
- src/components/ui/members/ShowPublication/Comments/Comments.view.jsx
- src/components/ui/members/ShowPublication/FullPublication/FullPublication.jsx
- src/components/ui/members/ShowPublication/MorePublications/MorePublications.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.view.jsx
- src/components/ui/reusables/EditProfile/EditProfile.jsx
- src/components/ui/reusables/PhoneInput/PhoneInput.view.jsx
- src/redux/utils/utilsSlice.js
> fix: 🐞 Severl fixes of homepage-new publication-preiew connections

- src/assets/icons/DefaultProfilePic.svg
- src/assets/icons/emptyProfilePic.svg
- src/assets/icons/smallUpload.svg
- src/components/AccountSettings/AccountSettings.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.view.jsx
- src/components/ui/reusables/EditProfile/EditProfile.jsx
- src/components/ui/reusables/EditProfile/EditProfile.style.js
- src/components/ui/reusables/EditProfile/EditProfile.view.jsx
- src/components/ui/reusables/PhoneInput/PhoneInput.view.jsx
- src/styles/AccountSettingsStyles.js
> Edit profile fixes

- src/components/AccountSettings/AccountSettings.jsx
- src/components/ui/reusables/EditProfile/EditProfile.jsx
- src/components/ui/reusables/EditProfile/EditProfile.style.js
- src/components/ui/reusables/EditProfile/EditProfile.view.jsx
- src/components/ui/reusables/PhoneInput/PhoneInput.style.js
- src/components/ui/reusables/PhoneInput/PhoneInput.view.jsx
- src/styles/AccountSettingsStyles.js
- src/styles/MainStyles.js
-   [ ] Bugfix
- Styling
-   [ ] Yes
-   [X ] No
> style: 🎨 styling fixes in editProfile

- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.jsx
- src/redux/auth/action.js
- src/utils/helpers/helperFunctions.js
-   [X] Bugfix
-   [ ] Yes
-   [X] No
> fix: 🐞 eslint fixes

- src/components/ui/reusables/EditProfile/EditProfile.jsx
- src/components/ui/reusables/PhoneInput/PhoneInput.view.jsx
-   [X] Bugfix
-   [ ] Yes
-   [X] No
> fix: 🐞 getting categories from server in edit profile

- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/pages/GeneralHome/GeneralHome.style.js
- src/components/pages/GeneralHome/GeneralHome.view.jsx
-   [ ] Bugfix
-   [x] Other... Please describe:
-   [ ] Yes
-   [x] No
> style: 🎨 homepage styling issues

- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/pages/GeneralHome/GeneralHome.style.js
- src/components/pages/GeneralHome/GeneralHome.view.jsx
- src/utils/helpers/helperFunctions.js
-   [ ] Bugfix
-   [ ] Other... Please describe: styling
-   [ ] Yes
-   [ X] No
> style: 🎨 home events styling

- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/pages/GeneralHome/GeneralHome.style.js
- src/components/pages/GeneralHome/GeneralHome.view.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.view.jsx
- src/components/ui/reusables/EditProfile/EditProfile.view.jsx
-   [ ] Bugfix
-   [X ] Feature
-   [ ] Yes
-   [ x] No
> feat: 🔥 generalHomepage events features and editprofile fix

- src/App.jsx
- src/components/layout/topbarParts/MakorLogo/MakorLogo.view.jsx
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.jsx
- src/components/ui/reusables/EditProfile/EditProfile.jsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
> fix: 🐞 adding footer to all users

- src/components/ui/author/AuthorsnewArticle/AuthorsNewArticle.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.view.jsx
- src/components/ui/reusables/SubHeader/SubHeader.view.jsx
- src/styles/AuthorsStyles.js
-   [ ] Bugfix
-   [ X] Other... Please describe: Styling
-   [ ] Yes
-   [ X] No
> style: 🎨 responsivity fixes of author forms

- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/pages/GeneralHome/GeneralHome.view.jsx
- src/components/ui/author/DeadArticle/DeadArticle.jsx
- src/components/ui/author/allPublications/AllPublications/AllPublications.view.jsx
- src/components/ui/members/ShowPublication/Comment/Comment.jsx
- src/components/ui/members/ShowPublication/Comment/Comment.view.jsx
- src/components/ui/members/ShowPublication/Comments/Comments.jsx
- src/components/ui/members/ShowPublication/FullPublication/FullPublication.jsx
- src/components/ui/members/ShowPublication/FullPublication/FullPublication.view.jsx
- src/components/ui/reusables/CategoriesAutoComplete/CategoriesAutoComplete.view.jsx
- src/components/ui/reusables/MessageAlert/MessageAlert.jsx
- src/components/ui/reusables/MessageAlert/MessageAlert.style.js
- src/components/ui/reusables/MessageAlert/MessageAlert.view.jsx
-   [ ] Bugfix
-   [X] Feature
-   [ ] Yes
-   [X] No
> Edit profile

- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.style.js
- src/components/ui/author/allPublications/AllPublicationsTabs/AllPublicationsTabs.view.jsx
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.style.js
- src/components/ui/author/allPublications/PublicationsTab/PublicationsTab.view.jsx
- src/components/ui/author/allPublications/TabPanel/TabPanel.style.js
-   [ ] Bugfix
-   [ ] Other... Please describe: Styling
-   [ ] Yes
-   [ X] No
> style: 🎨 responsivity fixes for AllPublications

- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/pages/GeneralHome/GeneralHome.style.js
- src/components/pages/GeneralHome/GeneralHome.view.jsx
- src/components/pages/LoginPage/LoginPage.jsx
> fix: 🐞 minor fixes in general home page

- src/components/pages/GeneralHome/GeneralHome.jsx
- src/components/pages/GeneralHome/GeneralHome.style.js
- src/components/pages/GeneralHome/GeneralHome.view.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/EventsSection/EventsSection.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/EventsSection/EventsSection.style.js
- src/components/pages/GeneralHome/GeneralHomeComponents/EventsSection/EventsSection.view.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/FocusIdeasSection/FocusIdeasSection.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/FocusIdeasSection/FocusIdeasSection.style.js
- src/components/pages/GeneralHome/GeneralHomeComponents/FocusIdeasSection/FocusIdeasSection.view.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/IndustryRecoursedSection/IndustryRecoursedSection.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/IndustryRecoursedSection/IndustryRecoursedSection.style.js
- src/components/pages/GeneralHome/GeneralHomeComponents/IndustryRecoursedSection/IndustryRecoursedSection.view.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/LatestNewsSection/LatestNewsSection.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/LatestNewsSection/LatestNewsSection.style.js
- src/components/pages/GeneralHome/GeneralHomeComponents/LatestNewsSection/LatestNewsSection.view.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/MorningNotesSection/MorningNotesSection.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/MorningNotesSection/MorningNotesSection.style.js
- src/components/pages/GeneralHome/GeneralHomeComponents/MorningNotesSection/MorningNotesSection.view.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/lastPublicationsSection/LastPublicationsSection.jsx
- src/components/pages/GeneralHome/GeneralHomeComponents/lastPublicationsSection/LastPublicationsSection.style.js
- src/components/pages/GeneralHome/GeneralHomeComponents/lastPublicationsSection/LastPublicationsSection.view.jsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> Split hompage
